package com.op.back.fcm.type;

public enum FcmType {
    CHAT,
    PAYMENT_COMPLETED,
    PAYMENT_RECEIVED,
    PAYMENT_REFUNDED,
    PAYMENT_REFUNDED_NOTICE,
    RESERVATION_CREATED,
    RESERVATION_RECEIVED,
    RESERVATION_ACCEPTED,
    RESERVATION_CANCELED
}
